INSERT INTO users VALUES (1, '123456','user');
INSERT INTO users VALUES (2, '123456','admin');
INSERT INTO users VALUES (3, '123456','dba');	
INSERT INTO roles VALUES (1, 'ROLE_USER',1);
INSERT INTO roles VALUES (2, 'ROLE_ADMIN',1);
INSERT INTO roles VALUES (3, 'ROLE_DBA',2);



